In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [5]:
data=pd.read_csv('sonar_dataset.csv', header=None)
data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [3]:
data.shape

(207, 61)

In [9]:
data.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [10]:
data.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [13]:
data[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [14]:
X=data.drop(60, axis='columns')
y=data[60]

In [15]:
X

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180   
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

         57      58      59  
0    0.0084  0.0090  0.0032  
1    0.0049  0.0052  0.0044  
2    0.0164  0.0095  0.0078  
3    0.0044  0.0040  0.0117  
4    0.0048  0.0107  0.0094  
..      ...     ...     ...  
203  0.0115  0.0193  0.0157  
204  0.0032  0.0062  0.0067  
205  0.0138  0.0077  0.0031  
206  0.0079  0.0036  0.0048  
207  0.0036  0.0061  0.0115  

[208 rows x 60 columns]

In [16]:
y=pd.get_dummies(y, drop_first=True)

In [17]:
y

R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

In [18]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=10)
len(X_train)

166

In [20]:
len(X_test)

42

In [22]:
X_train.shape

(166, 60)

In [23]:
import tensorflow as tf
from tensorflow import keras

model=keras.Sequential([
    keras.layers.Dense(60, input_shape=(60,), activation='relu'),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
21/21 [==============================] - 5s 9ms/step - loss: 0.6782 - accuracy: 0.5723
Epoch 2/100
21/21 [==============================] - 0s 8ms/step - loss: 0.6540 - accuracy: 0.5602
Epoch 3/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6358 - accuracy: 0.6747
Epoch 4/100
21/21 [==============================] - 0s 7ms/step - loss: 0.5984 - accuracy: 0.7108
Epoch 5/100
21/21 [==============================] - 0s 6ms/step - loss: 0.5814 - accuracy: 0.7410
Epoch 6/100
21/21 [==============================] - 0s 9ms/step - loss: 0.5341 - accuracy: 0.7470
Epoch 7/100
21/21 [==============================] - 0s 6ms/step - loss: 0.5167 - accuracy: 0.7590
Epoch 8/100
21/21 [==============================] - 0s 6ms/step - loss: 0.4754 - accuracy: 0.7651
Epoch 9/100
21/21 [==============================] - 0s 6ms/step - loss: 0.4319 - accuracy: 0.8434
Epoch 10/100
21/21 [==============================] - 0s 6ms/step - loss: 0.4237 - accuracy: 0.7952
Epoch 11/

In [24]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 13ms/step - loss: 1.5079 - accuracy: 0.7619


[1.5079184770584106, 0.761904776096344]

In [25]:
model.predict(X_test[:5])

1/1 [==============================] - 0s 178ms/step


array([[9.999962e-01],
       [9.999913e-01],
       [4.763477e-02],
       [7.868831e-07],
       [9.999988e-01]], dtype=float32)

In [26]:
y_pred=model.predict(X_test).reshape(-1)
print(y_pred[:10])

y_pred=np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 6ms/step
[9.9999619e-01 9.9999130e-01 4.7634900e-02 7.8688242e-07 9.9999881e-01
 7.5167727e-01 9.9682826e-01 1.6373551e-03 4.8848835e-04 9.9997318e-01]
[1. 1. 0. 0. 1. 1. 1. 0. 0. 1.]


In [27]:
y_test[:10]

R
58   1
63   1
35   1
19   1
59   1
56   1
83   1
105  0
121  0
76   1

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.89      0.76        18
           1       0.89      0.67      0.76        24

    accuracy                           0.76        42
   macro avg       0.78      0.78      0.76        42
weighted avg       0.79      0.76      0.76        42



In [35]:
dropout_model=keras.Sequential([
    keras.layers.Dense(60, input_shape=(60,), activation='relu'),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(30, activation='relu'),
    keras.layers.Dropout(0.25),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dropout(0.125),
    keras.layers.Dense(1, activation='sigmoid')
])

dropout_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

dropout_model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
21/21 [==============================] - 1s 10ms/step - loss: 0.6887 - accuracy: 0.5241
Epoch 2/100
21/21 [==============================] - 0s 6ms/step - loss: 0.6919 - accuracy: 0.5542
Epoch 3/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6892 - accuracy: 0.5482
Epoch 4/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6823 - accuracy: 0.5723
Epoch 5/100
21/21 [==============================] - 0s 7ms/step - loss: 0.6887 - accuracy: 0.5663
Epoch 6/100
21/21 [==============================] - 0s 6ms/step - loss: 0.6720 - accuracy: 0.5602
Epoch 7/100
21/21 [==============================] - 0s 6ms/step - loss: 0.6537 - accuracy: 0.5783
Epoch 8/100
21/21 [==============================] - 0s 6ms/step - loss: 0.6587 - accuracy: 0.6084
Epoch 9/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6663 - accuracy: 0.6205
Epoch 10/100
21/21 [==============================] - 0s 5ms/step - loss: 0.6449 - accuracy: 0.6205
Epoch 11

In [36]:
dropout_model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.8744 - accuracy: 0.7857


[0.8744373321533203, 0.7857142686843872]

In [37]:
dropout_y_pred=dropout_model.predict(X_test)
print(dropout_y_pred[:10])

2/2 [==============================] - 0s 9ms/step
[[9.9970657e-01]
 [9.9797148e-01]
 [7.4107224e-01]
 [5.5486589e-06]
 [9.9936754e-01]
 [4.4199625e-01]
 [7.6278543e-01]
 [3.3125281e-01]
 [1.0826631e-01]
 [9.9165136e-01]]


In [39]:
dropout_y_pred=dropout_y_pred.reshape(-1)
yp=np.round(dropout_y_pred)
print(yp[:10])

[1. 1. 1. 0. 1. 0. 1. 0. 0. 1.]


In [41]:
y_test[:10]

R
58   1
63   1
35   1
19   1
59   1
56   1
83   1
105  0
121  0
76   1

In [42]:
print(classification_report(y_test, yp))

              precision    recall  f1-score   support

           0       0.71      0.83      0.77        18
           1       0.86      0.75      0.80        24

    accuracy                           0.79        42
   macro avg       0.79      0.79      0.78        42
weighted avg       0.80      0.79      0.79        42

